/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cbc9c211-5748-435b-94f2-d7f5daf7f4c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_s1CRX9xvK",
    "aws_user_pools_web_client_id": "1qe2ee5khm4tgjna7gjaevfn2l",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "rpsplayerrecord-rpsdev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "rpsapi",
            "endpoint": "https://fkcgdca4yl.execute-api.us-east-1.amazonaws.com/rpsdev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
