/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fd02cba9-9454-4846-94ab-9e127af81ae7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5PBUxqBKU",
    "aws_user_pools_web_client_id": "1etvh9s9n547dnkc38ttlenecs",
    "oauth": {}
};


export default awsmobile;
